[general]
import = ["/home/gaxx/.config/alacritty/themes/catppuccin-mocha.toml"]

[font]
size = 16.0

[font.normal]
family = "JetBrainsMono NF"

[window]
opacity = 0.9

[selection]
save_to_clipboard = true

[terminal]
osc52 = "OnlyCopy"
